max_term	= 1
max_fact	= 2
max_blan	= 1
max_index	= 3 		# 8 by requirement
max_numlen	= 2
max_brac	= 2
max_func_num= 2
gen_diff    = 1
max_diff    = 2         # 2 by requirement
fun_def_brac	= 1
use_expr_func	= 1 	# 0 by requirement
gen_func_in_def = 1		# 1 by requirement